services:
  - type: web
    name: india-innovate-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DATABASE_URL
        fromDatabase:
          name: india-innovate-db
          property: connectionString

databases:
  - name: india-innovate-db
    plan: free
    databaseName: indiainnovatedb
    user: indiainnovate
